# STACKING
# several arrays can be stacked together along different axes.

# np.vstack: to stack arrays along vertical axis
# np.hstack: to stack arrays along horizontal axis
# np.column_stack: to stack 1-D arrays as colums into 2-D arrays
# np.row_stack: to stack 1-D arrays as rows into 2-D arrays
# np.concatenate: to stack arrays along specififed axis(axis is passed as argument)    

In [5]:
import numpy as np

In [7]:
a= np.array([[1,2],
            [3,4]])
b= np.array([[5,6],
            [7,8]])

In [8]:
a

array([[1, 2],
       [3, 4]])

In [9]:
b

array([[5, 6],
       [7, 8]])

In [10]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# for column

In [12]:
c= np.array([1,0])

In [14]:
np.column_stack((a,c))

array([[1, 2, 1],
       [3, 4, 0]])

# for row

In [15]:
np.row_stack((a,c))

array([[1, 2],
       [3, 4],
       [1, 0]])

# for concatenate 

In [16]:
np.concatenate((a,b), axis =1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# SPLITTING
# for splitting, we have these functions:

# np.hsplit: split along horizontal axis
# np.vsplit: split arrays along vertical axis
# np.array_split: split array along specific axis

In [17]:
import numpy as np

In [18]:
a=np.array([[1,3,5,6,9,11],
           [2,4,6,8,10,12]])

In [19]:
a

array([[ 1,  3,  5,  6,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [21]:
np.hsplit(a,2)

[array([[1, 3, 5],
        [2, 4, 6]]),
 array([[ 6,  9, 11],
        [ 8, 10, 12]])]

In [28]:
np.vsplit(a,2)

[array([[ 1,  3,  5,  6,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [25]:
np.array_split(a,2, axis=1)

[array([[1, 3, 5],
        [2, 4, 6]]),
 array([[ 6,  9, 11],
        [ 8, 10, 12]])]